############################################
# version : godcong/jbs:latest
# desc : 
############################################
#使用最新alpine镜像
FROM alpine:latest

#添加我的信息
MAINTAINER godcong (jumbycc@163.com)

COPY ./jbs /home/jbs

EXPOSE 1027

CMD ["/home/jbs"]